In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler, StandardScaler, MaxAbsScaler
import xgboost
import math
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
df_train = pd.read_csv('../dataset/train(preprocess).csv')
df_train.describe()

SalePrice  OverallQual    GrLivArea   GarageCars  TotalBsmtSF  \
count  1457.000000  1457.000000  1457.000000  1457.000000  1457.000000   
mean     12.023884     6.094029     7.265431     1.767330     6.746931   
std       0.399824     1.376839     0.329726     0.745925     1.145111   
min      10.460242     1.000000     5.811141     0.000000     0.000000   
25%      11.774520     5.000000     7.028201     1.000000     6.678342   
50%      12.001505     6.000000     7.285507     2.000000     6.898715   
75%      12.273731     7.000000     7.482119     2.000000     7.167038   
max      13.534473    10.000000     8.406485     4.000000     8.072779   

          1stFlrSF     FullBath  TotRmsAbvGrd    YearBuilt  
count  1457.000000  1457.000000   1457.000000  1457.000000  
mean   1158.658202     1.563487      6.505834  1971.257378  
std     372.094244     0.549961      1.604467    30.166849  
min     334.000000     0.000000      2.000000  1872.000000  
25%     882.000000     1.000000      5.000000  1954.000000  
50%    1086.000000     2.000000      6.000000  1973.000000  
75%    1390.000000     2.000000      7.000000  2000.000000  
max    3228.000000     3.000000     12.000000  2010.000000

In [3]:
y_train = df_train['SalePrice']
x_train = df_train.drop('SalePrice', axis=1)

In [4]:
x_train['1stFlrSF'] = np.log(x_train['1stFlrSF'])

In [5]:
x_train.head(5)

OverallQual  GrLivArea  GarageCars  TotalBsmtSF  1stFlrSF  FullBath  \
0            7   7.444249           2     6.752270  6.752270         2   
1            6   7.140453           2     7.140453  7.140453         2   
2            7   7.487734           2     6.824374  6.824374         2   
3            7   7.448334           3     6.628041  6.867974         1   
4            8   7.695303           3     7.043160  7.043160         2   

   TotRmsAbvGrd  YearBuilt  
0             8       2003  
1             6       1976  
2             6       2001  
3             7       1915  
4             9       2000

In [ ]:
columns = 

In [7]:
df_test = pd.read_csv('../dataset/test.csv')
df_test['GrLivArea'] = np.log(df_train['GrLivArea'])
df_test.ix[df_test['TotalBsmtSF']>0, 'TotalBsmtSF'] = np.log(df_test.ix[df_test['TotalBsmtSF']>0, 'TotalBsmtSF'])
df_test['1stFlrSF'] = np.log(df_test['1stFlrSF'])
x_test = df_test[columns]
x_test.isnull().any()
x_test.ix[x_test['GrLivArea'].isnull(), 'GrLivArea'] = x_train.loc[:, 'GrLivArea'].mean()
x_test.ix[x_test['GarageCars'].isnull(), 'GarageCars'] = math.ceil(x_train.loc[:, 'GarageCars'].mean())
x_test.ix[x_test['TotalBsmtSF'].isnull(), 'TotalBsmtSF'] = math.ceil(x_train.loc[:, 'TotalBsmtSF'].mean())
x_test.isnull().any()
x_test.head(5)

NameError: name 'columns' is not defined

In [168]:
columns = ['OverallQual', 'GrLivArea', 'GarageCars', 'TotalBsmtSF', '1stFlrSF', 'FullBath', 'TotRmsAbvGrd', 'YearBuilt']
scalars = []
for i in columns:
    minmax_scaler = MaxAbsScaler()
    temp = np.array(x_train[i]).reshape(-1,1)
    input(temp)
    x_train[i] = minmax_scaler.fit_transform(temp)
    temp = np.array(x_test[i]).reshape(-1,1)
    x_test[i] = minmax_scaler.transform(x_test[i])
    scalars.append(minmax_scaler)

[[7]
 [6]
 [7]
 ..., 
 [7]
 [5]
 [5]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)
D:\Programme Software\Anaconda\install\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


[[ 7.44424865]
 [ 7.14045304]
 [ 7.48773376]
 ..., 
 [ 7.75790621]
 [ 6.98286275]
 [ 7.13568735]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


[[2]
 [2]
 [2]
 ..., 
 [1]
 [1]
 [1]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


[[ 6.75227038]
 [ 7.14045304]
 [ 6.82437367]
 ..., 
 [ 7.04925484]
 [ 6.98286275]
 [ 7.13568735]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


[[ 6.75227038]
 [ 7.14045304]
 [ 6.82437367]
 ..., 
 [ 7.0800265 ]
 [ 6.98286275]
 [ 7.13568735]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


[[2]
 [2]
 [2]
 ..., 
 [2]
 [1]
 [1]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


[[8]
 [6]
 [6]
 ..., 
 [9]
 [5]
 [6]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


[[2003]
 [1976]
 [2001]
 ..., 
 [1941]
 [1950]
 [1965]]


''

D:\Programme Software\Anaconda\install\lib\site-packages\sklearn\preprocessing\data.py:818: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  warnings.warn(DEPRECATION_MSG_1D, DeprecationWarning)


In [169]:
x_train

OverallQual  GrLivArea  GarageCars  TotalBsmtSF  1stFlrSF  FullBath  \
0             0.7   0.885536        0.50     0.836424  0.835717  0.666667   
1             0.6   0.849398        0.50     0.884510  0.883761  0.666667   
2             0.7   0.890709        0.50     0.845356  0.844641  0.666667   
3             0.7   0.886022        0.75     0.821036  0.850037  0.333333   
4             0.8   0.915401        0.75     0.872458  0.871719  0.666667   
5             0.5   0.858469        0.50     0.827422  0.826722  0.333333   
6             0.8   0.884418        0.50     0.920391  0.920198  0.666667   
7             0.7   0.909407        0.50     0.868277  0.867542  0.666667   
8             0.7   0.889907        0.50     0.849592  0.857654  0.666667   
9             0.5   0.830541        0.25     0.854565  0.864142  0.333333   
10            0.5   0.826383        0.25     0.860543  0.859815  0.333333   
11            0.9   0.922032        0.75     0.875662  0.875656  1.000000   
12            0.5   0.810760        0.25     0.844274  0.843560  0.333333   
13            0.7   0.869473        0.75     0.905415  0.904648  0.666667   
14            0.6   0.848547        0.25     0.883623  0.882875  0.333333   
15            0.7   0.802943        0.50     0.832902  0.835427  0.333333   
16            0.6   0.822192        0.50     0.856179  0.855455  0.333333   
17            0.4   0.852561        0.50     0.000000  0.887052  0.666667   
18            0.5   0.834560        0.50     0.869058  0.868322  0.333333   
19            0.5   0.856443        0.25     0.859226  0.891091  0.333333   
20            0.8   0.924664        0.75     0.873856  0.873117  1.000000   
21            0.7   0.833917        0.25     0.799820  0.867654  0.333333   
22            0.8   0.891307        0.50     0.926903  0.927366  0.666667   
23            0.5   0.828649        0.50     0.860543  0.862172  0.333333   
24            0.5   0.828649        0.25     0.862903  0.862172  0.333333   
25            0.8   0.877627        0.75     0.911245  0.913132  0.666667   
26            0.5   0.809184        0.50     0.842634  0.841920  0.333333   
27            0.8   0.885118        0.75     0.921707  0.920926  0.666667   
28            0.5   0.877627        0.25     0.904583  0.913132  0.333333   
29            0.4   0.743929        0.25     0.774681  0.774025  0.333333   
...           ...        ...         ...          ...       ...       ...   
1427          0.5   0.894123        0.50     0.817040  0.816686  0.666667   
1428          0.6   0.816613        0.50     0.850370  0.849650  0.666667   
1429          0.4   0.817849        0.25     0.803461  0.850935  0.666667   
1430          0.6   0.891108        0.50     0.847492  0.850166  0.666667   
1431          0.5   0.835834        0.50     0.870385  0.869648  0.666667   
1432          0.6   0.872848        0.50     0.889982  0.908160  0.333333   
1433          0.4   0.804328        0.50     0.837577  0.836868  0.333333   
1434          0.8   0.900056        0.75     0.937262  0.936469  0.666667   
1435          0.6   0.846922        0.50     0.844274  0.881185  0.333333   
1436          0.7   0.886575        0.50     0.779126  0.859815  0.666667   
1437          0.6   0.933304        0.50     0.789905  0.898622  0.666667   
1438          0.6   0.802105        0.50     0.835261  0.834554  0.333333   
1439          1.0   0.904587        0.75     0.857773  0.858137  0.666667   
1440          0.6   0.815866        0.25     0.849592  0.848872  0.333333   
1441          0.7   0.863598        0.50     0.899296  0.898535  0.666667   
1442          0.6   0.810890        0.25     0.830192  0.843695  0.333333   
1443          0.5   0.842210        0.25     0.877025  0.876282  0.333333   
1444          0.8   0.909407        0.50     0.880317  0.879572  0.666667   
1445          0.4   0.857064        0.25     0.783861  0.826722  0.333333   
1446          0.5   0.766756        0.00     0.798451  0.797775  0.333333   
14

In [170]:
x_test

OverallQual  GrLivArea  GarageCars  TotalBsmtSF  1stFlrSF  FullBath  \
0             0.5   0.238797        0.25     0.840131  0.841369  0.333333   
1             0.6   0.233840        0.25     0.890918  0.890164  0.333333   
2             0.5   0.239490        0.50     0.846429  0.845712  0.666667   
3             0.6   0.238862        0.50     0.846161  0.845445  0.666667   
4             0.8   0.242742        0.50     0.886264  0.885514  0.666667   
5             0.6   0.235104        0.50     0.822178  0.821482  0.666667   
6             0.6   0.238646        0.50     0.874921  0.876178  0.666667   
7             0.6   0.241961        0.50     0.826328  0.825629  0.666667   
8             0.7   0.239383        0.50     0.888185  0.891276  0.333333   
9             0.4   0.231170        0.50     0.840131  0.839420  0.333333   
10            0.7   0.230573        0.50     0.897806  0.890906  0.666667   
11            0.6   0.243601        0.25     0.765538  0.764890  0.333333   
12            0.5   0.228302        0.25     0.775866  0.775210  0.333333   
13            0.6   0.236619        0.50     0.836280  0.835572  0.666667   
14            0.7   0.233721        0.25     0.833496  0.832790  0.333333   
15            0.9   0.227150        0.75     0.913129  0.915203  0.666667   
16            0.8   0.229968        0.75     0.909492  0.908723  0.666667   
17            0.9   0.234283        0.75     0.921270  0.920490  0.666667   
18            0.8   0.231744        0.75     0.930001  0.929213  0.666667   
19            0.9   0.234823        0.75     0.985246  0.977710  0.666667   
20            0.8   0.243940        0.75     0.919284  0.919685  0.666667   
21            0.8   0.231652        0.50     0.894681  0.893924  0.666667   
22            0.6   0.239569        0.50     0.890451  0.889697  0.666667   
23            0.7   0.230898        0.50     0.872458  0.871719  0.666667   
24            0.7   0.230898        0.50     0.737124  0.818361  0.666667   
25            0.7   0.237730        0.50     0.835115  0.834408  0.666667   
26            0.8   0.228071        0.75     0.916131  0.916565  0.666667   
27            0.8   0.238741        0.75     0.913518  0.912745  0.666667   
28            0.7   0.237730        0.50     0.880114  0.879369  0.666667   
29            0.6   0.218069        0.50     0.903240  0.902475  0.666667   
...           ...        ...         ...          ...       ...       ...   
1429          0.4   0.229338        0.25     0.800595  0.799918  0.333333   
1430          0.6   0.239543        0.25     0.851528  0.850807  0.666667   
1431          0.3   0.231926        0.00     0.000000  0.815840  0.333333   
1432          0.5   0.237080        0.00     0.804214  0.862172  0.666667   
1433          0.3   0.227355        0.00     0.665852  0.786684  0.333333   
1434          0.8   0.240731        0.50     0.911797  0.926188  0.666667   
1435          0.8   0.233493        0.50     0.913440  0.916640  0.666667   
1436          0.6   0.238936        0.50     0.915826  0.915051  0.666667   
1437          0.6   0.245046        0.50     0.918764  0.917986  0.666667   
1438          0.8   0.227026        0.50     0.905166  0.904399  0.666667   
1439          0.6   0.241329        0.50     0.870605  0.878553  0.666667   
1440          0.6   0.229049        0.50     0.916359  0.916941  0.333333   
1441          0.6   0.235813        0.50     0.895672  0.896870  0.666667   
1442          0.8   0.228321        0.75     0.923439  0.938250  0.666667   
1443          0.9   0.232829        0.75     0.931084  0.930296  0.666667   
1444          0.1   0.241961        0.25     0.000000  0.913132  0.333333   
1445          0.7   0.234909        1.00     0.887036  0.893743  0.666667   
1446          0.5   0.221664        0.25     0.690710  0.794994  0.333333   
1447          0.5   0.239543        0.25     0.837577  0.838292  0.333333   
1448          0.5   0.237506        0.75     0.917868  0.917091  0.666667   
14

In [171]:
kf = KFold(n_splits=10, shuffle=True, random_state=123456)

In [172]:
models = {}
for train_index, test_index in kf.split(x_train):
    xgb_regressor = xgboost.XGBRegressor()
    x = x_train.ix[train_index, :]
    y = y_train.ix[train_index]
    
    xgb_regressor.fit(x, y)
    y_predict = xgb_regressor.predict(x_train.ix[test_index,:])
    y_true = y_train.ix[test_index].values
    
    y_true = np.exp(y_true)
    y_predict = np.exp(y_predict)
    
    y_predict[0:10]
    y_true[0:10]
    
    error = np.linalg.norm(y_predict-y_true) / len(y_predict)
    input(error)
    models[error] = xgb_regressor

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 151122.515625 ,  341664.25     ,  157950.578125 ,  273885.09375  ,
        166909.734375 ,  241917.453125 ,  178274.484375 ,  215671.203125 ,
        190702.       ,   96715.4453125], dtype=float32)

array([ 143000.,  345000.,  207500.,  249700.,  177000.,  225000.,
        204750.,  198900.,  169500.,  100000.])

2221.49736291


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 135203.59375  ,  317009.5      ,  256739.5      ,   72793.234375 ,
        117161.7109375,  163706.234375 ,  137391.828125 ,  112629.9140625,
        220040.546875 ,  131832.890625 ], dtype=float32)

array([ 139000.,  325300.,  230000.,   68500.,  124900.,  158000.,
        136500.,  110000.,  214000.,  118964.])

2660.11623974


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 121674.359375 ,  131573.390625 ,  138457.90625  ,  319598.53125  ,
        223201.921875 ,  236683.328125 ,  117581.8046875,  109534.2421875,
        181430.5625   ,  136520.25     ], dtype=float32)

array([ 139400.,  144000.,  114500.,  385000.,  172500.,  219500.,
        127000.,  163500.,  181000.,  155000.])

2247.89364622


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 178554.71875 ,  183230.421875,  136019.40625 ,  155310.296875,
        265813.1875  ,  279338.125   ,  315471.375   ,  153340.375   ,
        141372.265625,  129591.      ], dtype=float32)

array([ 140000.,  129900.,  132000.,  159000.,  256300.,  277500.,
        309000.,  145000.,  141000.,  130000.])

2811.8822647


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 197050.53125  ,  157318.28125  ,  149118.5      ,  130559.9453125,
        262599.65625  ,  198359.046875 ,  172164.015625 ,  171540.734375 ,
        205165.671875 ,  209772.8125   ], dtype=float32)

array([ 208500.,  181500.,  157000.,  109000.,  239686.,  196500.,
        140000.,  168500.,  217000.,  174000.])

2403.35177447


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 202423.390625 ,  238633.625    ,  130530.9375   ,  157768.5625   ,
        103502.6796875,  143318.90625  ,  166832.875    ,  254618.640625 ,
        202387.671875 ,  178866.4375   ], dtype=float32)

array([ 223500.,  200000.,  129500.,  160000.,  113000.,  144900.,
        153500.,  250000.,  190000.,  259500.])

2157.67869821


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 113881.296875 ,  224041.109375 ,  109924.1484375,  138832.765625 ,
        132509.765625 ,  127029.59375  ,  283982.34375  ,  181403.390625 ,
        147343.546875 ,  310174.9375   ], dtype=float32)

array([ 118000.,  279500.,   90000.,  129900.,  154000.,  134800.,
        306000.,  165500.,  170000.,  319900.])

2335.598322


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 289544.4375   ,  123300.84375  ,  141670.53125  ,  149229.46875  ,
        126194.5078125,  129981.625    ,  254896.09375  ,  254896.09375  ,
        105440.765625 ,  118742.03125  ], dtype=float32)

array([ 250000.,  144000.,  149350.,  153000.,  130250.,  110000.,
        180000.,  244000.,  107400.,  135750.])

1825.78708184


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 258608.5625   ,  141240.734375 ,   98644.15625  ,  417095.9375   ,
         89135.1640625,  201786.1875   ,  107096.828125 ,  107249.828125 ,
        117727.5546875,  215115.15625  ], dtype=float32)

array([ 307000.,  149000.,   82000.,  438780.,   80000.,  185000.,
        128950.,  115000.,  115000.,  220000.])

2464.39621034


''

XGBRegressor(base_score=0.5, colsample_bylevel=1, colsample_bytree=1, gamma=0,
       learning_rate=0.1, max_delta_step=0, max_depth=3,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='reg:linear', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

array([ 102828.9296875,  215375.03125  ,   86280.453125 ,  304475.71875  ,
        200187.609375 ,  117264.328125 ,  176306.28125  ,  168503.671875 ,
        139256.171875 ,  220861.515625 ], dtype=float32)

array([  40000.,  179900.,  101000.,  317000.,  226000.,  129500.,
        178000.,  163990.,  180000.,  226000.])

2363.30303512


''

In [173]:
model = sorted(models.items(), key=lambda x: x[0])[0][1]

In [174]:
y_predict = model.predict(x_test)

In [175]:
y_predict = np.exp(y_predict)

In [176]:
y_predict

array([ 120178.1640625,  147625.5625   ,  138016.265625 , ...,
        136816.125    ,  136576.640625 ,  189437.859375 ], dtype=float32)

In [177]:
result = pd.DataFrame({'Id': range(len(y_predict)), 'SalePrice': y_predict})

In [178]:
result['Id'] += 1461 

In [179]:
result.to_csv('../submission/submission.csv', index=False)